name: threading
version: 0.0.1
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: This is the implementation of the cooperative, non-preemptive multitasking (software threads). Also can be used in conjunction with any third-party libraries for parallel computations (for the coordination and synchronization).
homepage: https://github.com/mezoni/threading
dev_dependencies:
  build_tools: any
  file_utils: any
